# Yazi keymap configuration with vim-like numbered navigation
# This enables commands like 5j, 10k, etc.

[mgr]
prepend_keymap = [
    # Basic vim navigation
    { on = [ "k" ], run = "arrow -1", desc = "Move cursor up" },
    { on = [ "j" ], run = "arrow 1", desc = "Move cursor down" },
    { on = [ "h" ], run = "leave", desc = "Go back to parent directory" },
    { on = [ "l" ], run = "enter", desc = "Enter directory or open file" },

    # Sort functionality
    { on = [ "s", "m" ], run = "sort mtime --reverse=no", desc = "Sort by modified time (oldest first)" },
    { on = [ "s", "r" ], run = "sort mtime --reverse", desc = "Sort by modified time (newest first)" },
    { on = [ "s", "n" ], run = "sort natural --reverse=no", desc = "Sort by name" },
    { on = [ "s", "s" ], run = "sort size", desc = "Sort by size" },
    { on = [ "s", "e" ], run = "sort extension", desc = "Sort by extension" },
    { on = [ "s", "c" ], run = "sort ctime", desc = "Sort by creation time" },

    # Vim-like numbered navigation (single digits) - using array syntax
    { on = [ "1", "j" ], run = "arrow 1", desc = "Move 1 down" },
    { on = [ "2", "j" ], run = "arrow 2", desc = "Move 2 down" },
    { on = [ "3", "j" ], run = "arrow 3", desc = "Move 3 down" },
    { on = [ "4", "j" ], run = "arrow 4", desc = "Move 4 down" },
    { on = [ "5", "j" ], run = "arrow 5", desc = "Move 5 down" },
    { on = [ "6", "j" ], run = "arrow 6", desc = "Move 6 down" },
    { on = [ "7", "j" ], run = "arrow 7", desc = "Move 7 down" },
    { on = [ "8", "j" ], run = "arrow 8", desc = "Move 8 down" },
    { on = [ "9", "j" ], run = "arrow 9", desc = "Move 9 down" },

    { on = [ "1", "k" ], run = "arrow -1", desc = "Move 1 up" },
    { on = [ "2", "k" ], run = "arrow -2", desc = "Move 2 up" },
    { on = [ "3", "k" ], run = "arrow -3", desc = "Move 3 up" },
    { on = [ "4", "k" ], run = "arrow -4", desc = "Move 4 up" },
    { on = [ "5", "k" ], run = "arrow -5", desc = "Move 5 up" },
    { on = [ "6", "k" ], run = "arrow -6", desc = "Move 6 up" },
    { on = [ "7", "k" ], run = "arrow -7", desc = "Move 7 up" },
    { on = [ "8", "k" ], run = "arrow -8", desc = "Move 8 up" },
    { on = [ "9", "k" ], run = "arrow -9", desc = "Move 9 up" },

    # Common double-digit movements
    { on = [ "1", "0", "j" ], run = "arrow 10", desc = "Move 10 down" },
    { on = [ "1", "5", "j" ], run = "arrow 15", desc = "Move 15 down" },
    { on = [ "2", "0", "j" ], run = "arrow 20", desc = "Move 20 down" },
    { on = [ "2", "5", "j" ], run = "arrow 25", desc = "Move 25 down" },
    { on = [ "3", "0", "j" ], run = "arrow 30", desc = "Move 30 down" },
    { on = [ "5", "0", "j" ], run = "arrow 50", desc = "Move 50 down" },

    { on = [ "1", "0", "k" ], run = "arrow -10", desc = "Move 10 up" },
    { on = [ "1", "5", "k" ], run = "arrow -15", desc = "Move 15 up" },
    { on = [ "2", "0", "k" ], run = "arrow -20", desc = "Move 20 up" },
    { on = [ "2", "5", "k" ], run = "arrow -25", desc = "Move 25 up" },
    { on = [ "3", "0", "k" ], run = "arrow -30", desc = "Move 30 up" },
    { on = [ "5", "0", "k" ], run = "arrow -50", desc = "Move 50 up" },

    # Jump commands
    { on = [ "g", "g" ], run = "arrow -99999", desc = "Jump to top" },
    { on = [ "G" ], run = "arrow 99999", desc = "Jump to bottom" },

    # Page navigation
    { on = [ "<C-u>" ], run = "arrow -5", desc = "Move up 5 lines" },
    { on = [ "<C-d>" ], run = "arrow 5", desc = "Move down 5 lines" },
    { on = [ "<C-b>" ], run = "arrow -10", desc = "Move up 10 lines" },
    { on = [ "<C-f>" ], run = "arrow 10", desc = "Move down 10 lines" },
]

[input]
keymap = [
    { on = [ "<Esc>" ], run = "close", desc = "Cancel input" },
    { on = [ "<Enter>" ], run = "close --submit", desc = "Submit input" },
    { on = [ "<C-c>" ], run = "close", desc = "Cancel input" },
    { on = [ "<Backspace>" ], run = "backspace", desc = "Delete previous character" },
    { on = [ "<Delete>" ], run = "delete", desc = "Delete current character" },
    { on = [ "<C-h>" ], run = "backspace", desc = "Delete previous character" },
    { on = [ "<D-Backspace>" ], run = "kill", desc = "Delete whole line before cursor" },
    { on = [ "<C-u>" ], run = "kill", desc = "Delete whole line before cursor" },
    { on = [ "<C-k>" ], run = "kill --dir=after", desc = "Delete line after cursor" },
    { on = [ "<Left>" ], run = "move -1", desc = "Move cursor left" },
    { on = [ "<Right>" ], run = "move 1", desc = "Move cursor right" },
    { on = [ "<C-a>" ], run = "move -999", desc = "Move to beginning of line" },
    { on = [ "<C-e>" ], run = "move 999", desc = "Move to end of line" },
]

[select]
keymap = [
    { on = [ "<Esc>" ], run = "close", desc = "Cancel selection" },
    { on = [ "<Enter>" ], run = "close --submit", desc = "Submit selection" },
    { on = [ "k" ], run = "arrow -1", desc = "Move cursor up" },
    { on = [ "j" ], run = "arrow 1", desc = "Move cursor down" },
]

[tasks]
keymap = [
    { on = [ "<Esc>" ], run = "close", desc = "Close task manager" },
    { on = [ "k" ], run = "arrow -1", desc = "Move cursor up" },
    { on = [ "j" ], run = "arrow 1", desc = "Move cursor down" },
]
